import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayOutProvider from "./layoutProvider";
import { WebProvider } from "./context/WebContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebProvider>
        <LayOutProvider>
        {children}
        </LayOutProvider>
        </WebProvider>
      </body>
    </html>
  );
}
